artworks = [
  { title: "daisy", description: "A mathematical approach for drawing a daisy" },
  { title: "white_cherry", description: "A natural shape generated by a fractal algorithm" },
  { title: "black_hole", description: "A simulation of an imaginary black hole vortex" }
]

artworks.each { |artwork| Artwork.create(artwork) }
